const provinceNames = {
  VN01: 'Hà Nội',
  VN02: 'Hà Giang',
  VN03: 'Cao Bằng',
  VN04: 'Bắc Kạn',
  VN05: 'Tuyên Quang',
  VN06: 'Lào Cai',
  VN07: 'Điện Biên',
  VN08: 'Lai Châu',
  VN09: 'Sơn La',
  VN10: 'Yên Bái',
  VN11: 'Hoà Bình',
  VN12: 'Thái Nguyên',
  VN13: 'Lạng Sơn',
  VN14: 'Quảng Ninh',
  VN15: 'Bắc Giang',
  VN16: 'Phú Thọ',
  VN17: 'Vĩnh Phúc',
  VN18: 'Bắc Ninh',
  VN19: 'Hải Dương',
  VN20: 'Hải Phòng',
  VN21: 'Hưng Yên',
  VN22: 'Thái Bình',
  VN23: 'Hà Nam',
  VN24: 'Nam Định',
  VN25: 'Ninh Bình',
  VN26: 'Thanh Hóa',
  VN27: 'Nghệ An',
  VN28: 'Hà Tĩnh',
  VN29: 'Quảng Bình',
  VN30: 'Quảng Trị',
  VN31: 'Thừa Thiên Huế',
  VN32: 'Phú Yên - Đắk Lắk',
  VN33: 'Đắk Lắk',
  VN34: 'Quảng Ngãi',
  VN35: 'Bình Định',
  VN36: 'Đà Nẵng',
  VN37: 'Khánh Hòa',
  VN38: 'Ninh Thuận',
  VN39: 'Bình Thuận',
  VN40: 'Kon Tum',
  VN41: 'Gia Lai',
  VN42: 'Quảng Nam',
  VN43: 'Đắk Nông',
  VN44: 'Lâm Đồng',
  VN45: 'Bình Phước',
  VN46: 'Tây Ninh',
  VN47: 'Bình Dương',
  VN48: 'Đồng Nai',
  VN49: 'Bà Rịa - Vũng Tàu',
  VN50: 'Hồ Chí Minh',
  VN51: 'Long An',
  VN52: 'Tiền Giang',
  VN53: 'Bến Tre',
  VN54: 'Trà Vinh',
  VN55: 'Vĩnh Long',
  VN56: 'Đồng Tháp',
  VN57: 'An Giang',
  VN58: 'Kiên Giang',
  VN59: 'Cần Thơ',
  VN60: 'Hậu Giang',
  VN61: 'Sóc Trăng',
  VN62: 'Bạc Liêu',
  VN63: 'Cà Mau'
};

export default provinceNames;
